local _, _, E = unpack(ElvUI_DuckTools)
local LSM = E.Libs.LSM

-- Fonts
LSM:Register("font", "Gilroy-Heavy", [[Interface\AddOns\ElvUI_DuckTools\Media\Fonts\Gilroy-Heavy.ttf]])
LSM:Register("font", "Gilroy-Bold", [[Interface\AddOns\ElvUI_DuckTools\Media\Fonts\Gilroy-Bold.ttf]])
LSM:Register("font", "Gilroy-Medium", [[Interface\AddOns\ElvUI_DuckTools\Media\Fonts\Gilroy-Medium.ttf]])
-- These are too light for my taste, but keeping them if someone enjoys them.
-- LSM:Register("font", "Gilroy Regular", [[Interface\AddOns\ElvUI_DuckyUI\Media\Fonts\Gilroy-Regular.ttf]])
-- LSM:Register("font", "Gilroy Light", [[Interface\AddOns\ElvUI_DuckyUI\Media\Fonts\Gilroy-Light.ttf]])

-- KMT StatusBars
LSM:Register("statusbar", "KMT01", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT01.tga]])
LSM:Register("statusbar", "KMT04", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT04.tga]])
LSM:Register("statusbar", "KMT07", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT07.tga]])
LSM:Register("statusbar", "KMT12", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT12.tga]])
LSM:Register("statusbar", "KMT15", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT15.tga]])
LSM:Register("statusbar", "KMT22", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT22.tga]])
LSM:Register("statusbar", "KMT25", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT25.tga]])
LSM:Register("statusbar", "KMT27", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT27.tga]])
LSM:Register("statusbar", "KMT28", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT28.tga]])
LSM:Register("statusbar", "KMT30", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT30.tga]])
LSM:Register("statusbar", "KMT31", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT31.tga]])
LSM:Register("statusbar", "KMT31-Border", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT31-Border.tga]])
LSM:Register("statusbar", "KMT32", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT32.tga]])
LSM:Register("statusbar", "KMT38", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT38.tga]])
LSM:Register("statusbar", "KMT40", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT40.tga]])
LSM:Register("statusbar", "KMT41", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT41.tga]])
LSM:Register("statusbar", "KMT43", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT43.tga]])
LSM:Register("statusbar", "KMT44", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT44.tga]])
LSM:Register("statusbar", "KMT31-Checkered", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT31_checkered.tga]])
LSM:Register("statusbar", "KMT32", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT32.tga]])
LSM:Register("statusbar", "KMT38", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT38.tga]])
LSM:Register("statusbar", "KMT40", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT40.tga]])
LSM:Register("statusbar", "KMT41", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT41.tga]])
LSM:Register("statusbar", "KMT43", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT43.tga]])
LSM:Register("statusbar", "KMT44", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT44.tga]])
LSM:Register("statusbar", "KMT44-Checkered", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT44_checkered.tga]])
LSM:Register("statusbar", "KMT44-Dark", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT44_dark.tga]])
LSM:Register("statusbar", "KMT44-Striped", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT44_striped.tga]])
LSM:Register("statusbar", "KMT45", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT45.tga]])
LSM:Register("statusbar", "KMT47", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT47.tga]])
LSM:Register("statusbar", "KMT48", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT48.tga]])
LSM:Register("statusbar", "KMT48-Dark", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT48_dark.tga]])
LSM:Register("statusbar", "KMT48-Striped", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT48_striped.tga]])
LSM:Register("statusbar", "KMT49", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT49.tga]])
LSM:Register("statusbar", "KMT51", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT51.tga]])
LSM:Register("statusbar", "KMT52", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT52.tga]])
LSM:Register("statusbar", "KMT53", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT53.tga]])
LSM:Register("statusbar", "KMT54", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT54.tga]])
LSM:Register("statusbar", "KMT55", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT55.tga]])
LSM:Register("statusbar", "KMT56", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT56.tga]])
LSM:Register("statusbar", "KMT57", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT57.tga]])
LSM:Register("statusbar", "KMT58", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT58.tga]])
LSM:Register("statusbar", "KMT61", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT61.tga]])
LSM:Register("statusbar", "KMT62", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT62.tga]])
LSM:Register("statusbar", "KMT63", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT63.tga]])
LSM:Register("statusbar", "KMT64", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT64.tga]])
LSM:Register("statusbar", "KMT65", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT65.tga]])
LSM:Register("statusbar", "KMT65-Dark", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT65_dark.tga]])
LSM:Register("statusbar", "KMT65-Striped", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT65_striped.tga]])
LSM:Register("statusbar", "KMT67", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\KMT\KMT67.tga]])

-- MaUI Statusbars
LSM:Register("statusbar", "MaUI1", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI1.tga]])
LSM:Register("statusbar", "MaUI2", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI2.tga]])
LSM:Register("statusbar", "MaUI3", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI3.tga]])
LSM:Register("statusbar", "MaUI4", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI4.tga]])
LSM:Register("statusbar", "MaUI4.1", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI4.1.tga]])
LSM:Register("statusbar", "MaUI5", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI5.tga]])
LSM:Register("statusbar", "MaUI6", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI6.tga]])
LSM:Register("statusbar", "MaUI7", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI7.tga]])
LSM:Register("statusbar", "MaUI8", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI8.tga]])
LSM:Register("statusbar", "MaUI9", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI9.tga]])
LSM:Register("statusbar", "MaUI10", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI10.tga]])
LSM:Register("statusbar", "MaUI11", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI11.tga]])
LSM:Register("statusbar", "MaUI12", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI12.tga]])
LSM:Register("statusbar", "MaUI13", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI13.tga]])
LSM:Register("statusbar", "MaUI14", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MaUI\MaUI14.tga]])

-- Misc Statusbars
LSM:Register("statusbar", "Melli", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\Melli.tga]])
LSM:Register("statusbar", "Melli Dark", [[Interface\AddOns\ElvUI_DuckTools\Media\StatusBars\MelliDark.tga]])
